spring:
  datasource: # Datasource configuration
    druid:
      url: jdbc:mysql://localhost:3306/vocabulary
      username: root
      password: 123456
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
#  jpa: # JPA configuration
#    hibernate:
#      ddl-auto: update
  mvc:
    view: # MVC view resolver
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.yejt.vocabularysearch.entity
  configuration:
    map-underscore-to-camel-case: true # _ to camel using reflections..
